export const GET_LOGIN_START = "GET_LOGIN_START";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_ERROR = "GET_LOGIN_ERROR";

export const LOGIN_START = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GET_VERIFY_START = "GET_VERIFY_START";
export const GET_VERIFY_SUCCESS = "GET_VERIFY_SUCCESS";
export const GET_VERIFY_ERROR = "GET_VERIFY_ERROR";

export const VERIFY_START = "VERIFY_START";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_ERROR = "VERIFY_ERROR";

export const GET_AUTH_FROM_LOCAL_STORAGE = "GET_AUTH_FROM_LOCAL_STORAGE";
